### ISSUE TITLE
Updating to latest version of Lean-game-maker: compilation error after game done

### ISSUE THREAD

**Issue by stanescuUW** [mpedramfar/Lean-game-maker#13]
After updating the game maker and running it in the real-number-game, I get the following error after the game is apparently done. Note that just prior to this I compiled with the previous version with no error. What can this be due to?

Traceback (most recent call last):
  File "/home/dan/.virtualenvs/lgame/bin/make-lean-game", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/dan/GitProjects/Lean-game-maker/bin/make-lean-game", line 154, in <module>
    Fire(render_lean_project)
  File "/home/dan/.virtualenvs/lgame/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/dan/.virtualenvs/lgame/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/dan/.virtualenvs/lgame/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/dan/GitProjects/Lean-game-maker/bin/make-lean-game", line 148, in render_lean_project
    proc = subprocess.run(['msguniq', str(pot_path)], stdout=subprocess.PIPE)
  File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msguniq'

**Comment by stanescuUW** [comment]
Solved. I needed the gettext package, of which msguniq is a part.
