### ISSUE TITLE
Installing new version fails

### ISSUE THREAD

**Issue by stanescuUW** [mpedramfar/Lean-game-maker#16]
I get these errors belo when trying to install the new version of the game maker on the new version of Ubuntu. Apparently at least part of it is either because of [bdist_wheel] or because of the python package termcolor (that is a separate error message which I didn't copy here). Whatever I tried I couldn't get to install with either python 3.8.3, 3.8.0 or 3.7.2. I also tried on two Linux distributions, Ubuntu 20.04 and Linux Mint 20. Any hint? This is the first of several error messages I get.

ERROR: Command errored out with exit status 1:
   command: /home/dan/.virtualenvs/lean-game/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-msmlfhh9/fire/setup.py'"'"'; __file__='"'"'/tmp/pip-install-msmlfhh9/fire/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cu0ppvct
       cwd: /tmp/pip-install-msmlfhh9/fire/
  Complete output (92 lines):
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fire
  copying fire/parser_fuzz_test.py -> build/lib/fire
  copying fire/__init__.py -> build/lib/fire
  copying fire/test_components_test.py -> build/lib/fire
  copying fire/inspectutils_test.py -> build/lib/fire
  copying fire/helptext.py -> build/lib/fire
  copying fire/trace_test.py -> build/lib/fire
  copying fire/custom_descriptions.py -> build/lib/fire
  copying fire/inspectutils.py -> build/lib/fire
  copying fire/test_components_py3.py -> build/lib/fire
  copying fire/test_components_bin.py -> build/lib/fire
  copying fire/fire_import_test.py -> build/lib/fire
  copying fire/core_test.py -> build/lib/fire
  copying fire/core.py -> build/lib/fire
  copying fire/parser_test.py -> build/lib/fire
  copying fire/value_types.py -> build/lib/fire
  copying fire/main_test.py -> build/lib/fire
  copying fire/parser.py -> build/lib/fire
  copying fire/docstrings_test.py -> build/lib/fire
  copying fire/completion_test.py -> build/lib/fire
  copying fire/fire_test.py -> build/lib/fire
  copying fire/docstrings.py -> build/lib/fire
  copying fire/completion.py -> build/lib/fire
  copying fire/decorators_test.py -> build/lib/fire
  copying fire/decorators.py -> build/lib/fire
  copying fire/formatting_windows.py -> build/lib/fire
  copying fire/__main__.py -> build/lib/fire
  copying fire/test_components.py -> build/lib/fire
  copying fire/testutils.py -> build/lib/fire
  copying fire/testutils_test.py -> build/lib/fire
  copying fire/formatting.py -> build/lib/fire
  copying fire/trace.py -> build/lib/fire
  copying fire/helptext_test.py -> build/lib/fire
  copying fire/interact.py -> build/lib/fire
  copying fire/custom_descriptions_test.py -> build/lib/fire
  copying fire/formatting_test.py -> build/lib/fire
  copying fire/docstrings_fuzz_test.py -> build/lib/fire
  copying fire/interact_test.py -> build/lib/fire
  creating build/lib/fire/console
  copying fire/console/__init__.py -> build/lib/fire/console
  copying fire/console/console_pager.py -> build/lib/fire/console
  copying fire/console/console_attr_os.py -> build/lib/fire/console
  copying fire/console/encoding.py -> build/lib/fire/console
  copying fire/console/platforms.py -> build/lib/fire/console
  copying fire/console/files.py -> build/lib/fire/console
  copying fire/console/text.py -> build/lib/fire/console
  copying fire/console/console_attr.py -> build/lib/fire/console
  copying fire/console/console_io.py -> build/lib/fire/console
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-msmlfhh9/fire/setup.py", line 46, in <module>
      setup(
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/install.py", line 557, in run
      self.run_command(cmd_name)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 984, in run_command
      cmd_obj.ensure_finalized()
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
      self.set_undefined_options('install',('install_layout','install_layout'))
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
      setattr(self, dst_option, getattr(src_cmd_obj, src_option))
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: install_layout
  ----------------------------------------
  ERROR: Failed building wheel for fire

**Comment by stanescuUW** [comment]
Progress. I was finally able to install fire and termcolor in Mint 20 (needed `pip3 install fire` instead of `pip install fire`). Now the only error that I still get when trying to install is:
```
Installing collected packages: Lean-game-maker
  Running setup.py develop for Lean-game-maker
    ERROR: Command errored out with exit status 1:
     command: /home/dan/.virtualenvs/leanGame-380/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dan/Lean-game-maker/setup.py'"'"'; __file__='"'"'/home/dan/Lean-game-maker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/dan/Lean-game-maker/
    Complete output (30 lines):
    running develop
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dan/Lean-game-maker/setup.py", line 17, in <module>
        setup(
      File "/home/dan/.virtualenvs/leanGame-380/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 984, in run_command
        cmd_obj.ensure_finalized()
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/dan/.virtualenvs/leanGame-380/lib/python3.8/site-packages/setuptools/command/develop.py", line 56, in finalize_options
        easy_install.finalize_options(self)
      File "/home/dan/.virtualenvs/leanGame-380/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
        self.set_undefined_options(
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/dan/.virtualenvs/leanGame-380/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/home/dan/.pyenv/versions/3.8.0/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/dan/.virtualenvs/leanGame-380/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dan/Lean-game-maker/setup.py'"'"'; __file__='"'"'/home/dan/Lean-game-maker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by stanescuUW** [comment]
Finally figured it all out! The problem was an outdated `setuptools`. I did `pip3 install --upgrade setuptools` and then everything worked well.
